KERNEL_C_SOURCES = \
	$(KERNEL_DIR)/blk.c \
	$(KERNEL_DIR)/blkdev.c \
	$(KERNEL_DIR)/buddy.c \
	$(KERNEL_DIR)/ctype.c \
	$(KERNEL_DIR)/kmalloc.c \
	$(KERNEL_DIR)/printk.c \
	$(KERNEL_DIR)/sched.c \
	$(KERNEL_DIR)/exec.c \
	$(KERNEL_DIR)/string.c \
	$(KERNEL_DIR)/vsprintf.c
