KERNEL_C_SOURCES = \
	$(KERNEL_DIR)/mm.c \
	$(KERNEL_DIR)/blk.c \
	$(KERNEL_DIR)/blkdev.c \
	$(KERNEL_DIR)/init.c \
	$(KERNEL_DIR)/buddy.c \
	$(KERNEL_DIR)/fork.c \
	$(KERNEL_DIR)/pagecache.c \
	$(KERNEL_DIR)/semaphore.c \
	$(KERNEL_DIR)/ctype.c \
	$(KERNEL_DIR)/memchunk.c \
	$(KERNEL_DIR)/kmalloc.c \
	$(KERNEL_DIR)/printk.c \
	$(KERNEL_DIR)/sched.c \
	$(KERNEL_DIR)/exec.c \
	$(KERNEL_DIR)/string.c \
	$(KERNEL_DIR)/rbtree.c \
	$(KERNEL_DIR)/vsprintf.c \
	$(KERNEL_DIR)/file.c \
	$(KERNEL_DIR)/fdt.c \
	$(KERNEL_DIR)/open.c \
	$(KERNEL_DIR)/read.c \
	$(KERNEL_DIR)/close.c
