ARCH_C_SOURCES = $(ARCH_DIR)/8259a.c \
		$(ARCH_DIR)/dma.c \
		$(ARCH_DIR)/floppy.c \
		$(ARCH_DIR)/idt.c \
		$(ARCH_DIR)/syscalls.c \
		$(ARCH_DIR)/irq.c \
		$(ARCH_DIR)/mm.c \
		$(ARCH_DIR)/pci.c \
		$(ARCH_DIR)/pc_keyb.c \
		$(ARCH_DIR)/setup.c \
		$(ARCH_DIR)/task.c \
		$(ARCH_DIR)/timer.c \
		$(ARCH_DIR)/serio.c \
		$(ARCH_DIR)/vga.c \
		$(ARCH_DIR)/ide.c

ARCH_ASM_SOURCES = $(ARCH_DIR)/entry.S \
			$(ARCH_DIR)/intr.S \
			$(ARCH_DIR)/io.S \
			$(ARCH_DIR)/user.S
